# print("Hey, what's your first name?")
first_name = input("Hey, what's your first name? : ")
last_name = input("And your last name : ")
name = (first_name + " " + last_name + ".")
print("Well, pleased to meet you, " + name)